name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: issue
    attributes:
      label: What is the issue?
      description: Please describe what the issue is.
      placeholder: ex. Game crashes when [...]
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: To Reproduce
      description: Please describe what steps to take to recreate the issue.
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft Version
      description: What version of Minecraft are you running?
      options:
        - 1.21.4
        - 1.21.1
      default: 0
    validations:
      required: true
  - type: input
    id: rc-version
    attributes:
      label: Williams-Console Version
      description: What Williams Console version are you on?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log or crash report
      description: Please upload your log or crash report here.
  - type: textarea
    id: extras
    attributes:
      label: Additional Context
      description: Put any extra info you feel is nessecary here.
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement
      description: If you do not fill out this form correctly, your issue will be immediately closed.
      options:
        - label: I understand and have fully filled out the form.
          required: true
