name: Dev Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-devs:
    runs-on: ubuntu-latest
    env:  
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACK_NAME: Williams-Console
      OUTPUT: artifacts
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Packwiz
      run: go install github.com/packwiz/packwiz@latest

    - name: Create short commit SHA
      id: vars
      run: |
          shortSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV

    - name: Prepare builds
      run: |
          mkdir Revisited-temp
          cp -r ./versions/modrinth/1.21.1/* ./Revisited-modr-1211-temp/
          cp ./LICENSE ./Revisited-modr-1211-temp/
          cp ./README.md ./Revisited-modr-1211-temp/
          cp ./CREDITS.md ./Revisited-modr-1211-temp/

          mkdir Classic-temp
          cp -r ./versions/archived/classic/* ./Classic-temp/
          cp ./LICENSE ./Classic-temp/
          cp ./README.md ./Classic-temp/
          cp ./CREDITS.md ./Classic-temp/
          
    - name: Create Revisited builds
      run: |
          cd ./Revisited-modr-1211-temp/
          packwiz refresh
          packwiz modrinth export --output ${PACK_NAME}-Revisited-Modrinth-1.21.1-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack

    - name: Create Classic build
      run: |
          cd ./Classic-temp/
          packwiz refresh
          packwiz modrinth export --output ${PACK_NAME}-Classic-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack

    - name: Prepare artifacts
      run: |
          mkdir $OUTPUT
          
          mv ./Revisited-modr-1211-temp/${PACK_NAME}-Revisited-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack ${OUTPUT}/
          mv ./Classic-temp/${PACK_NAME}-Classic-dev-${{ env.COMMIT_SHORT_SHA }}.mrpack ${OUTPUT}/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "Williams-Console-dev-${{ env.COMMIT_SHORT_SHA }}"
        path: artifacts
